WebApplication3/Controllers/PredictController.cs
using Microsoft.Cognitive.CustomVision;
using Microsoft.Cognitive.CustomVision.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
//using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Helper;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class PredictController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase ImageFile)
        {
            ViewData["ImageContentType"] = ImageFile.ContentType;

            ViewData["ImageContentLength"] = ImageFile.ContentLength;

            ViewData["ImageExtension"] = Path.GetExtension(ImageFile.FileName);

            ViewData["ImageBase64String"] = Convert.ToBase64String(ResizePicture(ImageFile));

            return View();
        }

        [HttpPost]
        public ActionResult Predict(PredictRequest request)
        {
            PredictionViewModel modelData = new PredictionViewModel();

            byte[] thePictureAsBytes = new byte[request.ImageContentLength];

            thePictureAsBytes = Convert.FromBase64String(request.ImageBase64String);

            using (MemoryStream stream = new MemoryStream(thePictureAsBytes))
            {
                using (System.Drawing.Bitmap bmp = new System.Drawing.Bitmap(stream))
                {
                    System.Drawing.Rectangle rect = new System.Drawing.Rectangle(request.ImageCoordsX, request.ImageCoordsY, (request.ImageCoordsX2 - request.ImageCoordsX), (request.ImageCoordsY2 - request.ImageCoordsY));
                    System.Drawing.Bitmap cropped = bmp.Clone(rect, bmp.PixelFormat);

                    using (MemoryStream croppedStream = new MemoryStream())
                    {
                        string filename = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + request.ImageExtension);

                        cropped.Save(filename);

                        Predict(filename, request.ImageContentType, modelData);
                    }
                }
            }

            return Json(modelData);
        }

        [HttpPost]
        public ActionResult MinimumPredictionPercentage(int minimumPredictionPercentage, IList<Prediction> predictions)
        {
            IList<Tag> strongTags;
            IList<Image> images = GetImagesByPrediction(minimumPredictionPercentage, predictions, out strongTags);

            return Json(new { Images = images, StrongTagStrings = strongTags.GetStrings() });
        }

        [HttpPost]
        public ActionResult HandleVoice(string strongTagStrings, string voice)
        {
            if (voice != null && voice.Trim().Length > 0)
            {
                IList<Tag> voiceTags;
                string intent;
                string entities;
                IList<Image> images = GetImagesByVoice(voice, strongTagStrings, out voiceTags, out intent, out entities);

                if (images != null)
                {
                    return Json(new { ChangeInventory = true, Voice = voice, Images = images, StrongTagStrings = voiceTags.GetStrings(), Intent = intent, Entities = entities });
                }
            }

            return Json(new { ChangeInventory = false });
        }

        private void Predict(string filename, string contentType, PredictionViewModel modelData)
        {
            try
            {
                modelData.PredictionImageBase64String = Convert.ToBase64String(System.IO.File.ReadAllBytes(filename));
                modelData.PredictionImageContentType = contentType;

                using (FileStream fileStream = new FileStream(filename, FileMode.Open, FileAccess.Read))
                {

                    if (Settings.ApplyDummyPredictions)
                    {
                        modelData.Predictions = GetDummyPredictions();
                    }
                    else
                    {
                        var predictionKey = "61923266b04e4173b6ff56c7bb2804bf";
                        var projectID = "141bef78-2d42-45dc-9687-0d3b12ed702a";

                        PredictionEndpointCredentials predictionEndpointCredentials = new PredictionEndpointCredentials(predictionKey);
                        PredictionEndpoint endpoint = new PredictionEndpoint(predictionEndpointCredentials);

                        modelData.Predictions = GetPredictions(endpoint.PredictImage(Guid.Parse(projectID), fileStream));
                    }


                    IList<Tag> strongTags;

                    modelData.Images = GetImagesByPrediction(Settings.MinimumPredictionPercentage, modelData.Predictions, out strongTags);

                    modelData.StrongTags = strongTags;
                }
            }
            catch
            {
                throw;
            }
            finally
            {
                if (System.IO.File.Exists(filename))
                {
                    System.IO.File.Delete(filename);
                }
            }
        }

        public IList<Prediction> GetDummyPredictions()
        {
            IList<Prediction> predictions = new List<Prediction>();

            IList<Tag> tags = Tag.GetTagsFromDB();


            foreach (Tag tag in tags)
            {
                double dummyPrediction;

                dummyPrediction = Settings.DummyPredictions.Where(dp => dp.Key.ToLower().Trim() == tag.Name.ToLower().Trim()).FirstOrDefault()?.Value ?? GetDummyDouble(tag.ID);

                predictions.Add(new Prediction()
                {
                    MappingTagID = tag.ID,
                    MappingTagString = tag.Name,
                    Probability = dummyPrediction,
                    Tag = tag.MapString
                });
            }


            return predictions;
        }

        public double GetDummyDouble(int id)
        {
            switch (id)
            {
                case 1:
                    return .75;
                case 2:
                    return .70;
                case 4:
                    return .56;
                case 8:
                    return .30;
                case 16:
                    return .55;
                case 32:
                    return .75;
                default:
                    return .90;
            }
        }

        public IList<Prediction> GetPredictions(ImagePredictionResultModel results)
        {
            IList<Prediction> predictions = new List<Prediction>();

            IList<Tag> tags = Tag.GetTagsFromDB();


            foreach (ImageTagPrediction prediction in results.Predictions)
            {
                predictions.Add(new Prediction() {
                                                    Tag = prediction.Tag,
                                                    Probability = prediction.Probability,
                                                    MappingTagID = tags.First(tm => tm.MapString.ToString() == prediction.Tag).ID,
                                                    MappingTagString = tags.First(tm => tm.MapString.ToString() == prediction.Tag).Name
                });
            }

            return predictions;
        }

        private IList<Image> GetImagesByPrediction(int minimumPredictionPercentage, IList<Prediction> predictions, out IList<Tag> strongTags)
        {
            IList<Image> dbImages = Image.GetImagesFromDB();

            IList<Tag> tags = Tag.GetTagsFromDB();

            IList<int> strongTagIDs = new List<int>();


            var groupByCategory = predictions.Where(
                                            prediction => (prediction.Probability * 100) >= minimumPredictionPercentage
                                        ).Join(
                                                tags, 
                                                prediction => prediction.MappingTagID, 
                                                tag => tag.ID, 
                                                (prediction, tag) => new { Tag = tag, Prediction = prediction }
                                            ).GroupBy(joinResult => joinResult.Tag.Category);

            foreach (var group in groupByCategory)
            {
                strongTagIDs.Add(group.OrderByDescending(line => line.Prediction.Probability).First().Tag.ID);
            }


            strongTags = tags.Where(tag => strongTagIDs.Count > 0 && strongTagIDs.Contains(tag.ID)).ToList();

            return dbImages.Where(image => strongTagIDs.All(strongTag => (strongTag & image.Tags) == strongTag)).ToList();
        }

        private IList<Image> GetImagesByVoice(string voice, string strongTagStrings, out IList<Tag> voiceTags, out string intent, out string entities)
        {
            intent = "None";
            entities = "";

            voiceTags = Tag.GetTagsFromDB().Where(t => strongTagStrings.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(val => val.Trim().ToLower()).Contains(t.Name.Trim().ToLower())).ToList();

            VoiceResponse voiceResponse = null;
            if (Settings.ApplyDummyRASANLP)
            {
                voiceResponse = new VoiceResponse() {
                    intent = new VoiceResponseIntent() { name = Settings.DummyRASANLPIntent },
                    entities = Settings.DummyRASANLPEntities.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select<string, VoiceResponseEntity>(entity => new VoiceResponseEntity { value = entity.Trim() }).ToList()
                };
            }
            else
            {
                voiceResponse = SendVoiceRequest(voice);
            }

            if (voiceResponse != null && voiceResponse.intent != null && voiceResponse.entities != null && voiceResponse.entities.Count > 0)
            {

WebApplication3/Controllers/TagImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;
using System.IO;
using Newtonsoft.Json;

namespace WebApplication3.Controllers
{
    public class TagImagesController : Controller
    {
        public ActionResult Index()
        {
            IList<Image> images = new List<Image>();

            IList<Image> dbImages = Image.GetImagesFromDB();

            string[] filenames = Directory.GetFiles(Server.MapPath(@"~\ImageFiles"));

            filenames.ToList().ForEach(fn =>
            {
                Image image = dbImages.FirstOrDefault(i => i.Filename == Path.GetFileName(fn));
                images.Add(new Image() { Filename = Path.GetFileName(fn), Tags = (image == null ? 0 : image.Tags) });
            });

            return View(images.OrderBy(image => image.Tags));
        }

        [HttpPost]
        public ActionResult Index(List<Image> images)
        {
            Image.SaveImagestoDB(images);

            TempData["Message"] = "Updated successfully!";
            return RedirectToAction("Index");
        }
    }
}

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Custom Vision PoC</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @RenderSection("OptionalScript", false)

    <style>
        .navbar-inverse {
            background-color: #4eaaff !important;
            border-color: #4eaaff !important;
        }

        .navbar-brand {
            color: #fff !important;
        }

        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
        }

        html {
            overflow-y: scroll;
        }

        .flexbox-parent {
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: flex-start; /* align items in Main Axis */
            align-items: stretch; /* align items in Cross Axis */
            align-content: stretch; /* Extra space in Cross Axis */
            background-color: #fff;
        }

        .flexbox-item {
            padding: 8px;
        }

        .flexbox-item-grow {
            flex: 1; /* same as flex: 1 1 auto; */
        }

        /*.flexbox-item.header {
            background: rgba(255, 0, 0, .1);
        }*/

        .flexbox-item.footer {
            background-color: #76BAF9;
            color: #fff;
        }

        .flexbox-item.content {
            background: #F2F2F2;
        }

        .fill-area {
            display: flex;
            flex-direction: row;
            justify-content: flex-start; /* align items in Main Axis */
            align-items: stretch; /* align items in Cross Axis */
            align-content: stretch; /* Extra space in Cross Axis */
        }

        .fill-area-content {
            background: #fff;
            border: 0px solid #fff;
            /* Needed for when the area gets squished too far and there is content that can't be displayed */
            overflow: auto;
        }
    </style>
</head>
<body>
    <div style="display: flex; flex-direction: column; justify-content:flex-start; width: 100%; min-height:100%;">
        <div class="navbar navbar-inverse" style="margin: 0px; border-radius: 0px;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @Html.ActionLink("Prediction", "Index", "Predict", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Tag Images", "Index", "TagImages", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Settings", "Index", "Settings", new { area = "" }, new { @class = "navbar-brand" })
                    </ul>
                </div>
            </div>
        </div>
        <div style="flex-grow: 1; display:flex; flex-direction: row; ">
            <div style="background-color: #F2F2F2; min-width: 8%;">&nbsp;</div>
            <div style="background-color: #fff; min-width: 3%;">&nbsp;</div>
            <div style="flex-grow:1; display:flex; flex-direction: column; ">
                @RenderBody()
            </div>
            <div style="background-color: #fff;  min-width: 3%;">&nbsp;</div>
            <div style="background-color: #F2F2F2;  min-width: 8%;">&nbsp;</div>
        </div>
        <div class="footer">
            <div class="text-center" style="background-color: #76baf9; color: #fff; padding: 10px">
                <span>&copy; @DateTime.Now.Year - Custom Vision PoC</span>
            </div>
        </div>
    </div>
</body>
</html>